### ISSUE TITLE
How to get the `yolox_320x320_nodecode.pt` file?

### ISSUE THREAD

**Issue by hu-qi** [modelbox-ai/modelbox-solutions#2]
In the inference flowunit, we found that we needed model file `yolox_320x320_nodecode.pt` and `hand_pose_256x256.pt`, 
can you help me how to get it?

Best wishes 
Thanks!

**Comment by pymumu** [comment]
The page is here: https://modelbox-ai.com/modelbox-book/solution/hand-pose-detection.html
model file download link: http://download.modelbox-ai.com/solutions/hand_pose_detection/

**Comment by hu-qi** [comment]
> The page is here: https://modelbox-ai.com/modelbox-book/solution/hand-pose-detection.html model file download link: http://download.modelbox-ai.com/solutions/hand_pose_detection/

Thanks!
